version: "3"
services:
  di-mysql:
    image: vstandera/main_repo:dictionary_di-mysql
    ports:
      - 6604:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=dictionnarydb
      - MYSQL_USER=vasekuser
      - MYSQL_PASSWORD=vasekpass
  rabbitmq2:
    image: vstandera/main_repo:dictionary_rabbitmq2
    ports:
      - 5672:5672
      - 15672:15672
  spring-boot-webapp:
    image: vstandera/main_repo:dictionary-mysql2
    ports:
      - 8080:8080
    depends_on:
      - di-mysql
      - rabbitmq2
  dictionaryweb-prod:
        container_name: dictioanay-prod
        build:
          context: ./web-dictionary/
          dockerfile: Dockerfile.prod
        ports:
          - '3000:80'